/**
 * SourceApi
 * A Web API for controlling a source.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef OAI_OAIVeinApiHandler_H
#define OAI_OAIVeinApiHandler_H

#include <QObject>

#include "OAIProblemDetails.h"
#include "OAIVeinGetRequest.h"
#include "OAIVeinGetResponse.h"
#include "OAIVeinSet.h"
#include <QList>
#include <QString>

namespace OpenAPI {

class OAIVeinApiHandler : public QObject
{
    Q_OBJECT

public:
    OAIVeinApiHandler();
    virtual ~OAIVeinApiHandler();
    QList<OAIVeinGetResponse> generateBulkAnswer(QList<OAIVeinGetRequest> oai_vein_get_request);

public slots:
    virtual void apiV1VeinGet(qint32 entity_id, QString component_name);
    virtual void apiV1VeinPost(QList<OAIVeinGetRequest> oai_vein_get_request);
    virtual void apiV1VeinPut(OAIVeinSet oai_vein_set);
};

}

#endif // OAI_OAIVeinApiHandler_H
