/**
 * SourceApi
 * A Web API for controlling a source.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QVariantMap>
#include <QDebug>

#include <VfConvenientCode/vfatomicclientcomponentfetcher.h>

#include "OAIVeinApiHandler.h"
#include "OAIVeinApiRequest.h"
#include "veinentrysingleton.h"



namespace OpenAPI {

OAIVeinApiHandler::OAIVeinApiHandler(){

}

OAIVeinApiHandler::~OAIVeinApiHandler(){

}

void OAIVeinApiHandler::apiV1VeinGetInfoPost(OAIVeinGet oai_vein_get) {
    Q_UNUSED(oai_vein_get);
    auto reqObj = qobject_cast<OAIVeinApiRequest*>(sender());
    if( reqObj != nullptr )
    {
        VeinEntrySingleton::getInstance().subscribeToEntity(0);

        QPair<VfCmdEventItemEntityPtr, VfAtomicClientComponentFetcherPtr> getterPair = VeinEntrySingleton::getInstance().triggerGetComponent(0, "EntityName");
        VfCmdEventItemEntityPtr item = getterPair.first;
        connect(getterPair.second.get(), &VfAtomicClientComponentFetcher::sigGetFinish, [reqObj,item](bool ok, QVariant data){
            OAIVeinGetResponse res;

            QJsonObject wJson;
            wJson.insert("ReceivedEntityID", data.toString());
            wJson.insert("ReceivedComponentName", "oai_vein_get.getComponentName()");
            wJson.insert("ReceivedMiscInfo", "oai_vein_get.getMiscFieldForInfo()");

            QJsonDocument wDoc(wJson);

            res.setReturnInformation(OAIObject(wDoc.toJson(QJsonDocument::Compact)));
            reqObj->apiV1VeinGetInfoPostResponse(res);
            VeinEntrySingleton::getInstance().removeItem(item);
        });
    }
}
void OAIVeinApiHandler::apiV1VeinSetInfoPost(OAIVeinSet oai_vein_set) {
    Q_UNUSED(oai_vein_set);
    auto reqObj = qobject_cast<OAIVeinApiRequest*>(sender());
    if( reqObj != nullptr )
    {
        OAIProblemDetails res;

        res.setStatus(200);
        res.setDetail(oai_vein_set.getComponentName());
        res.setTitle(oai_vein_set.getMiscFieldForInfo());
        res.setType(QString::number(oai_vein_set.getEntityId()));

        reqObj->apiV1VeinSetInfoPostResponse(res);
    }
}


}
