/**
 * SourceApi
 * A Web API for controlling a source.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QVariantMap>
#include <QDebug>

#include "OAIVeinApiHandler.h"
#include "OAIVeinApiRequest.h"
#include "veinentrysingleton.h"



namespace OpenAPI {

OAIVeinApiHandler::OAIVeinApiHandler(){

}

OAIVeinApiHandler::~OAIVeinApiHandler(){

}

void OAIVeinApiHandler::apiV1VeinGetInfoPost(OAIVeinGet oai_vein_get) {
    Q_UNUSED(oai_vein_get);
    auto reqObj = qobject_cast<OAIVeinApiRequest*>(sender());
    if( reqObj != nullptr )
    {
        TaskSimpleVeinGetterPtr task = VeinEntrySingleton::getInstance().getFromVein(oai_vein_get.getEntityId(), oai_vein_get.getComponentName());
        connect(task.get(), &TaskTemplate::sigFinish, this, [reqObj, task](bool ok, int taskId){

            OAIVeinGetResponse res;
            QJsonObject wJson;
            if (ok)
                wJson.insert("ReturnInformation", task->getValue().toString());
            else
                wJson.insert("ReturnInformation", "Timeout or not existing entity or component");
            QJsonDocument wDoc(wJson);

            res.setReturnInformation(OAIObject(wDoc.toJson(QJsonDocument::Compact)));
            reqObj->apiV1VeinGetInfoPostResponse(res);
        });
        task->start();
    }
}
void OAIVeinApiHandler::apiV1VeinSetInfoPost(OAIVeinSet oai_vein_set) {
    Q_UNUSED(oai_vein_set);
    auto reqObj = qobject_cast<OAIVeinApiRequest*>(sender());
    if( reqObj != nullptr )
    {
        TaskSimpleVeinSetterPtr task = VeinEntrySingleton::getInstance().setToVein(oai_vein_set.getEntityId(),oai_vein_set.getComponentName(), oai_vein_set.getMiscFieldForInfo());

        OAIProblemDetails res;

        res.setStatus(200);
        res.setDetail(oai_vein_set.getComponentName());
        res.setTitle(oai_vein_set.getMiscFieldForInfo());
        res.setType(QString::number(oai_vein_set.getEntityId()));

        reqObj->apiV1VeinSetInfoPostResponse(res);
    }
}






}
