/**
 * SourceApi
 * A Web API for controlling a source.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef OAI_OAIVeinApiHandler_H
#define OAI_OAIVeinApiHandler_H

#include <QObject>

#include "OAIProblemDetails.h"
#include "OAIVeinGet.h"
#include "OAIVeinGetResponse.h"
#include "OAIVeinSet.h"
#include <QString>

namespace OpenAPI {

class OAIVeinApiHandler : public QObject
{
    Q_OBJECT

public:
    OAIVeinApiHandler();
    virtual ~OAIVeinApiHandler();


public slots:
    virtual void apiV1VeinGetInfoPost(OAIVeinGet oai_vein_get);
    virtual void apiV1VeinSetInfoPost(OAIVeinSet oai_vein_set);
    virtual void apiV1VeinGetInfoPostResponse(bool ok, QVariant data);
    

};

}

#endif // OAI_OAIVeinApiHandler_H
